server {
    listen 80;
    server_name _; # Catch all
    root /var/www/public;

    index index.php index.html;

    location / {
        # This ensures that even if Nginx stripped the prefix, 
        # we pass the URI correctly to index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass recipes_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        # Ensure SCRIPT_FILENAME is absolute
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # Pass the headers from the Gateway through
        fastcgi_param HTTP_X_FORWARDED_PREFIX $http_x_forwarded_prefix;
    }
}
